import Web3Modal from "web3modal";
import { Web3Provider } from "@ethersproject/providers";
import { WalletConnectProvider } from "@walletconnect/web3-provider";
import Head from "next/head";
import Drawer from "../components/Drawer/Drawer";
import { Grid, Typography, Button } from "@mui/material";
export default function Home() {
  const handleConnect = async () => {
    const web3Modal = new Web3Modal({
      cacheProvider: true, // optional
      providerOptions: {
        walletconnect: {
          package: WalletConnectProvider,
          options: {
            rpc: {
              31337: "http://localhost:8545/",
            },
          },
        },
      }, // required
    });

    if (!provider) {
      try {
        const rawProvider = await web3Modal.connect();

        if (!rawProvider.on) {
          console.log("yee");
          return;
        }

        rawProvider.on("accountsChanged", (accounts) => {
          console.log(accounts);
          // dispatch(setConnectedAddress(accounts[0]));
        });

        // Subscribe to chainId change
        rawProvider.on("chainChanged", (chainId) => {
          console.log(chainId);
        });

        // Subscribe to provider connection
        rawProvider.on("connect", (info) => {
          console.log(info);
        });

        // Subscribe to provider disconnection
        rawProvider.on("disconnect", (error) => {
          console.log(error);
        });

        const connectedProvider = new Web3Provider(rawProvider, "any");
        const connectedAddress = await connectedProvider
          .getSigner()
          .getAddress();

        return {
          connected: true,
          connectedAddress,
        };
      } catch (error) {
        console.error(error);
      }
    }
  };
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Drawer>
        <Grid container>
          <Grid item xs={12}>
            <Typography variant="subtitle1">Hello</Typography>
          </Grid>
        </Grid>
      </Drawer>
    </div>
  );
}
